version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    depends_on:
      - frontend

  web:
    build: ../backend
    restart: always
    volumes:
      - django_static:/app/django_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py makemigrations --no-input
        python3 manage.py migrate --no-input
        python3 manage.py collectstatic --no-input
        gunicorn --bind 0.0.0.0:8000 foodgram.wsgi:application
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
      - django_static:/var/html/django_static/
    depends_on:
      - backend

volumes:
  media_value:
  django_static: