# Generated by Django 2.2.19 on 2022-08-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220815_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
